# Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

# What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
!pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
## initially Lets import numpy

import numpy as np

In [20]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)
print(arr)

[1 2 3 4 5]


In [4]:
type(arr)

numpy.ndarray

In [5]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [6]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [7]:
type(arr)

numpy.ndarray

In [8]:
## check the shape of the array

arr.shape

(3, 5)

In [11]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [12]:
arr.shape

(3, 5)

# Indexing

In [22]:
## Accessing the array elements

arr

array([1, 2, 3, 4, 5])

In [23]:
arr[3]

4

In [24]:
arr1

NameError: name 'arr1' is not defined